const streetTypeChoices = [
  "ALY", // Alley
  "ANX", // Annex
  "ARC", // Arcade
  "AVE", // Avenue
  "BCH", // Beach
  "BND", // Bend
  "BLF", // Bluff
  "BLFS", // Bluffs
  "BTM", // Bottom
  "BLVD", // Boulevard
  "BR", // Branch
  "BRG", // Bridge
  "BRK", // Brook
  "BRKS", // Brooks
  "BG", // Burg
  "BGS", // Burgs
  "BYP", // Bypass
  "CP", // Camp
  "CYN", // Canyon
  "CPE", // Cape
  "CSWY", // Causeway
  "CTR", // Center
  "CTRS", // Centers
  "CIR", // Circle
  "CIRS", // Circles
  "CLF", // Cliff
  "CLFS", // Cliffs
  "CLB", // Club
  "CMN", // Common
  "CMNS", // Commons
  "COR", // Corner
  "CORS", // Corners
  "CT", // Court
  "CTS", // Courts
  "CV", // Cove
  "CVS", // Coves
  "CRK", // Creek
  "CRES", // Crescent
  "CRST", // Crest
  "XING", // Crossing
  "XRD", // Crossroad
  "XRDS", // Crossroads
  "CURV", // Curve
  "DL", // Dale
  "DM", // Dam
  "DV", // Divide
  "DR", // Drive
  "DRS", // Drives
  "EST", // Estate
  "ESTS", // Estates
  "EXPY", // Expressway
  "EXT", // Extension
  "EXTS", // Extensions
  "FALL", // Fall
  "FLS", // Falls
  "FRY", // Ferry
  "FLD", // Field
  "FLDS", // Fields
  "FLT", // Flat
  "FLTS", // Flats
  "FRD", // Ford
  "FRDS", // Fords
  "FRST", // Forest
  "FRG", // Forge
  "FRGS", // Forges
  "FRK", // Fork
  "FRKS", // Forks
  "FT", // Fort
  "FWY", // Freeway
  "GDN", // Garden
  "GDNS", // Gardens
  "GTWY", // Gateway
  "GLN", // Glen
  "GLNS", // Glens
  "GRN", // Green
  "GRNS", // Greens
  "GRV", // Grove
  "GRVS", // Groves
  "HBR", // Harbor
  "HBRS", // Harbors
  "HVN", // Haven
  "HTS", // Heights
  "HWY", // Highway
  "HL", // Hill
  "HLS", // Hills
  "HOLW", // Hollow
  "INLT", // Inlet
  "IS", // Island
  "ISS", // Islands
  "ISLE", // Isle
  "JCT", // Junction
  "JCTS", // Junctions
  "KY", // Key
  "KYS", // Keys
  "KNL", // Knoll
  "KNLS", // Knolls
  "LK", // Lake
  "LKS", // Lakes
  "LNDG", // Landing
  "LN", // Lane
  "LGT", // Light
  "LGTS", // Lights
  "LF", // Loaf
  "LCK", // Lock
  "LCKS", // Locks
  "LDG", // Lodge
  "LOOP", // Loop
  "MALL", // Mall
  "MNR", // Manor
  "MNRS", // Manors
  "MDW", // Meadow
  "MDWS", // Meadows
  "MEWS", // Mews
  "ML", // Mill
  "MLS", // Mills
  "MSN", // Mission
  "MTWY", // Motorway
  "MT", // Mount
  "MTN", // Mountain
  "MTNS", // Mountains
  "NCK", // Neck
  "ORCH", // Orchard
  "OVAL", // Oval
  "PARK", // Park
  "PKY", // Parkway
  "PKYS", // Parkways
  "PASS", // Pass
  "PSGE", // Passage
  "PATH", // Path
  "PIKE", // Pike
  "PNE", // Pine
  "PNES", // Pines
  "PL", // Place
  "PLZ", // Plaza
  "PT", // Point
  "PTS", // Points
  "PRT", // Port
  "PRTS", // Ports
  "PR", // Prairie
  "RADL", // Radial
  "RAMP", // Ramp
  "RNCH", // Ranch
  "RPD", // Rapid
  "RPDS", // Rapids
  "RST", // Rest
  "RDG", // Ridge
  "RDGS", // Ridges
  "RIV", // River
  "RD", // Road
  "RDS", // Roads
  "RT", // Route
  "ROW", // Row
  "RUE", // Rue
  "RUN", // Run
  "SHL", // Shoal
  "SHLS", // Shoals
  "SHR", // Shore
  "SHRS", // Shores
  "SKWY", // Skyway
  "SPG", // Spring
  "SPGS", // Springs
  "SPUR", // Spur
  "SPRS", // Spurs
  "SQ", // Square
  "SQS", // Squares
  "STA", // Station
  "STRA", // Stravenue
  "STRM", // Stream
  "ST", // Street
  "STS", // Streets
  "SMT", // Summit
  "TER", // Terrace
  "TRWY", // Throughway
  "TRCE", // Trace
  "TRAK", // Track
  "TRFY", // Trafficway
  "TRL", // Trail
  "TRLR", // Trailer
  "TUNL", // Tunnel
  "TPKE", // Turnpike
  "UPAS", // Underpass
  "UN", // Union
  "UNS", // Unions
  "VLY", // Valley
  "VLYS", // Valleys
  "VIA", // Viaduct
  "VW", // View
  "VWS", // Views
  "VLG", // Village
  "VLGS", // Villages
  "VL", // Ville
  "VIS", // Vista
  "WALK", // Walks
  "WALL", // Wall
  "WAY", // Way
  "WL", // Well
  "WLS", // Wells
];

export default streetTypeChoices;
