# docker-compose.yaml
version: "3"

services:
  app:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    command: ["python3", "app.py"]
    ports:
      - "5001:5000"
    volumes:
      - ./src/data:/app/src/data
    env_file:
      - ./.env
